baseURL = "https://responsereadyinc.github.io/"
languageCode = "en-us"
title = "Response Ready / Intervention Rapide Inc."
theme = "minimal"

[params]
  accent = "#c9201b"
  backgroundColor = "#eeeadf"
  showBorder = true

[[menu.main]]
  name = "Home"
  pre = "<img src='/img/cpr.jpg' style='height: 20px; width: 20px;' alt='cpr'>"
  url = "/"
  weight = 1

[[menu.main]]
  url = "/courses/"
  name = "Courses"
  weight = 2

[[menu.main]]
  url = "/staff/"
  name = "Staff Portfolios"
  weight = 3

[[menu.main]]
  url = "/contact/"
  name = "Contact"
  weight = 4

[[menu.icon]]
    url = "mailto:responsereadyinc@outlook.com"
    name = "envelope-o"
    weight = 1
