baseURL = "https://responsereadyinc.github.io/"
languageCode = "en-us"
title = "Response Ready / Intervention Rapide Inc."
theme = "minimal"

[params]
  accent = "#c9201b"
  backgroundColor = "#eeeadf"
  showBorder = true

[[menu.main]]
  name = "Home"
  post = "<span class='alert'>Home</span>"
  pre = "<i class='fa fa-road'></i>"
  url = "/"
  weight = 1

[[menu.main]]
  url = "/courses/"
  name = "Courses"
  weight = 2

[[menu.main]]
  url = "/staff/"
  name = "Staff Portfolios"
  weight = 3

[[menu.main]]
  url = "/contact/"
  name = "Contact"
  weight = 4

[[menu.icon]]
    url = "mailto:responsereadyinc@outlook.com"
    name = "envelope-o"
    weight = 1
