baseURL = "https://responsereadyinc.github.io/"
languageCode = "en-us"
theme = "hello-friend-ng"

[languages]
  [languages.en]
    title = "Response Ready / Intervention Rapide Inc."

    [languages.en.params.logo]
      path = "/img/cpr.jpg"
      alt = "Your example logo alt text"

[params]
  defaultTheme = "light"

[[menu.main]]
  url = "/courses/"
  name = "Courses"
  weight = 1

[[menu.main]]
  url = "/staff/"
  name = "Staff Portfolios"
  weight = 2

[[menu.main]]
  url = "/contact/"
  name = "Contact"
  weight = 3
