baseURL = "https://responsereadyinc.github.io/"
languageCode = "en-us"
theme = "den"
rssLimit = 20

[languages]
  [languages.en]
    title = "Response Ready / Intervention Rapide Inc."

    [languages.en.params.logo]
      path = "/img/cpr.jpg"
      alt = "Your example logo alt text"

[params]
  logoTitle = "Response Ready"
  siteLogoImage = "img/cpr.jpg"
  headerImage = "img/backdrop.jpg"

[[menu.main]]
  url = "/courses/"
  name = "Courses"
  weight = 1

[[menu.main]]
  url = "/targetedspecialty/"
  name = "Targeted Specialty"
  weight = 2

[[menu.main]]
  url = "/staff/"
  name = "Staff Portfolios"
  weight = 3

[[menu.main]]
  url = "/contact/"
  name = "Contact"
  weight = 4
