baseURL = "https://responsereadyinc.ca/"
languageCode = "en-us"
theme = "den"
rssLimit = 20

[languages]
  [languages.en]
    title = "Response Ready Inc."

    [languages.en.params.logo]
      path = "/img/cpr.png"
      alt = "Your example logo alt text"

[params]
  logoTitle = "Response Ready Inc."
  siteLogoImage = "img/cpr.png"
  headerImage = "img/backdrop.jpg"
  customFavicon = "favicon.ico"

[[menu.main]]
  url = "/courses/"
  name = "Courses"
  weight = 1

[[menu.main]]
  url = "/targetedspecialty/"
  name = "Targeted Specialty"
  weight = 2

[[menu.main]]
  url = "/ade/"
  name = "AED Sale"
  weight = 3

[[menu.main]]
  url = "/staff/"
  name = "Staff Portfolios"
  weight = 4

[[menu.main]]
  url = "/contact/"
  name = "Contact"
  weight = 5


[[menu.sitemap]]
  url = "/courses/"
  name = "Courses"
  weight = 1

[[menu.sitemap]]
  url = "/targetedspecialty/"
  name = "Targeted Specialty"
  weight = 2

[[menu.sitemap]]
  url = "/ade/"
  name = "AED Sale"
  weight = 3

[[menu.sitemap]]
  url = "/staff/"
  name = "Staff Portfolios"
  weight = 4

[[menu.sitemap]]
  url = "/contact/"
  name = "Contact"
  weight = 5
